services:
  DIP\Formation\Services\TwitterClient: # we make an interface as a type hint
    autowire: true
    public: true

  DIP\Formation\Services\UppercaseTransformer: ~

  DIP\Formation\Services\Rot13Transformer:
    autowire: true

  # create an alias to the service 'Rot13Transformer', so when the autowire system
  # found a TransformerInterface as a type hint it will replaced by an instance of the class 'Rot13Transformer'
  DIP\Formation\Services\TransformerInterface: '@DIP\Formation\Services\Rot13Transformer'