imports:
  - {resource: service_autowire.yml}

parameters:
    mailer.transport: sendmail

services:
    mailer:
        class:     DIP\Formation\Services\Mailer
        arguments: ['%mailer.transport%']
    newsletter_manager:
        class:     DIP\Formation\Services\NewsletterManager
        deprecated: The "%service_id%" service is deprecated since 2.8 and will be removed in 3.0.
        #calls:
        #    - [setMailer, ['@mailer']]
        #calls: # different way to use setter injection
         # - method: setLogger
          #  arguments:
           #    - '@logger'
        # arguments: ['@mailer']
        arguments: # a different way to pass arguments to contructor
          - '@mailer'
        tags: [newsletter.name]
    # another way to create an alias for the service newsletter_manager
    newsletter.manager.alias: '@newsletter_manager'